awesome-devblog/awesome-devblog

- README.md
> Add EFL Korea Community.

- README.md
> Add my blog / document

- Korea-Dev-RSS.opml
- README.md
- opmlGenerator/index.js
blog.naver.com/pjt3591oo 블로그를 추가하였습니다.
확인해 보시고 merge해주시면 감사하겠습니다 ^^
> 박정태님 블로그 추가

- Korea-Dev-RSS.opml
- README.md
> 임정택 미디엄 주소 및 RSS 추가

- Korea-Dev-RSS.opml
> 데일리호텔 Product팀 블로그 추가

- README.md
README.md 파일에는 빼먹었네요. 번거롭게 해드려 죄송합니다.
> 데일리호텔 Product 팀 블로그를 OPML뿐 아니라 README에도 추가한다

- README.md
박석제 블로그 추가
김남윤 키워드 Node.JS 추가 (본인)
가나다라 순으로 추가하였습니다.
제 첫 pull requst 입니다...
좋은 사이트 있으면 종종 pull requst 시키겠습니다.
감사합니다.
> 박서제 님 블로그 추가, 김남윤 님 Node.JS 키워드 추가

- Korea-Dev-RSS.opml
- README.md
kimjihyok.info 블로그와 RSS 피드를 추가하였습니다.
확인해 보시고 merge해주시면 감사하겠습니다! 
안드로이드 / 오픈소스 관련 기술 블로그입니다!
> 김지혁 블로그 주소 및 RSS 추가

- Korea-Dev-RSS.opml
- README.md
> 정재광님의 블로그를 추가합니다!

- README.md
Jin Park님 blog 추가합니다. 감사합니다 :)
> Jin Park님 blog 추가

- Korea-Dev-RSS.opml
- README.md
제 블로그를 추가하였습니다. 반영 해주시면 감사하겠습니다!
> 엘키 (김성훈) 블로그 추가.

- README.md
> Update blog URL

- README.md
- opmlGenerator/index.js
우영준 개발자 블로그 추가를 요청합니다.
본인의 블로그에서는 Serverside 이슈를 많이 다루고 있고, 추가로 보안적이슈에대해서도 얘기를 하고있습니다. 가끔 front 쪽도 얘기를 하고있어요 !
> 우영준 개발자 블로그 추가

- opmlGenerator/index.js
드라마앤컴패니, 라인, 스포카, 우아한형제들, 카카오, 레진 기술블로그 추가
> 팀 기술블로그 추가

- README.md
- opmlGenerator/index.js
아래 로지스팟 기술 블로그를 추가합니다.
http://engineering.logi-spot.com/
> 로지스팟 기술 블로그를 추가합니다.

- README.md
> fix a typo in the description

- README.md
> 주영익 블로그 추가

- README.md
- opmlGenerator/index.js
> 정민혁 블로그 업데이트

- README.md
부족하지만 블로그 내용 추가하고 있어요~
머지해주시면 감사하겠습니다.
> 김정원 블로그 추가

- README.md
블로그를 추가하고 싶습니다.
머지해주시면 감사하겠습니다^^
> 황지현 블로그 추가

- README.md
> 박준영 블로그 추가

- README.md
> 송재윤 블로그 추가

- README.md
> fix anchor -2

- README.md
- domestic_team.md
서한교님 같은 경우는 http:// 가 빠져있어서 하이퍼링크가 안 걸리던 부분을 수정 했고,
EFL Korea Community의 경우 표 블럭을 구분 하는 "|" 대신 "("로 되어 있어 블럭 오류가 있던 부분을 수정 했습니다.
오픈된 공간에 보내는 첫 pr이다 보니 혹시 잘못 된 부분이 있다면 알려주세요!!
> fix 서한교님 및 EFL Korea Community 링크 수정

- README.md
> 최용석 블로그 추가

- README.md
- db.json
블로그, rss, github, linkedin 정보 추가하여 풀리퀘스트 요청합니다. @sarojaba
> append information (blog, rss, github, linkedin)

- README.md
> 박성범 블로그 추가

- README.md
- db.json
안녕하세요, 새벽에 메일 드렸던 김형록입니다. 말씀하신 풀리퀘스트 보내드립니다.
감사합니다.
김형록 드림.
> 김형록 님 블로그 추가

- README.md
- db.json
> 배수한 블로그 추가

- db.json
> 유준상 블로그 추가

- db.json
> 김형철 블로그 추가

- db.json
readme >>> db.json 으로 재수정하였습니다.
> 김중근님(av9300@gmail.com) 블로그 추가

- db.json
> 김중근 블로그 수정

- db.yml
> 김중근 blog 추가 in db.yml

- README.md
가나다순으로 추가 했습니다. 항상 좋은 자료 감사합니다.
> 진민완 개발 블로그추가 했습니다.

- db.json
> 김형철 블로그 주소 수정

- db.json
> 권성준 블로그 추가했습니다.

- db.json
> 김강호 블로그 추가

- README.md
> Update KIMJUNHEE LinkedIn

- db.yml
> SANGCHUL_LEE add

- README.md
- db.yml
안녕하세요. 노경모라고 합니다.
db.yml, README.md 두 파일에 제 블로그를 추가했습니다.
> Update db.yml and README.md: 노경모 블로그 추가

- README.md
이참에 도메인을 아예 구매했어요 ㅎㅎ 
http://daily-devblog.mooo.com 으로 접속하면 http://daily-devblog.com 으로 redirect 처리는 해두긴 했습니다.
> Daily Devblog 도메인 변경되었습니다!

- README.md
Tony Lee님 Link 오류 수정  및 닉네임 추가
> 안영회 - Tony Lee 님 Link 오류 수정

- db.yml
부족하지만 저도 다른 개발자 분들과 함께 이번 기회로 블로그 관리도 꾸준히 쉬지않고 하고싶어요^^
> 백승엽 블로그 추가

- db.yml
> 백승엽 블로그 rss 추가 및 description 수정본 드려요^^

- db.yml
> 이성준 블로그 정보 추가 요청드립니다!

- README.md
- db.yml
이름 순서가 맞지 않는 부분 수정하고,
제 블로그도 추가했습니다.
> 김영전 블로그 추가

- db.yml
> 이름 및 링크 수정

- README.md
안녕하세요.
인터넷 방황하던중에 제 이름이 보여 들어오게 되었습니다!
현재 적혀있는 블로그가 더이상 사용하지 않는곳이라 셀프 정보 업데이트를 해봤습니다 :D
감사합니다.
> update developer list

- db.yml
> 양상현 블로그 추가 

- db.yml
블로그는 따로 없어 개인 사이트 URL을 등록합니다!
향후 블로그를 개설하게 된다면..! 업데이트 하겠습니다
_**PS** 다른 리스트들은 한글 순으로 정리가 되어 있길래, `노`씨 리스트 정리를 살짝 했습니다!_
> 개발자 노우현 추가

- README.md
- db.yml
> 박성범 블로그 정보 수정

- README.md
- deleted
- elliekwon.com
- confluence.swtool.review
- changed
- seokjun.kr -> seokjun.kim
> Chang a link and remove dead links

- db.yml
> fix blog - 노아론

- db_opensource.yml
The date-fns blog actually has RSS 😉
> Add RSS for blog.date-fns.org

- README.md
- db.yml
> Add RSS for yous.be

- README.md
> rss 추가 부탁드립니다.

- README.md
- db.yml
README.md에 윤우식 정보 추가와 db.yml에 description 수정하였습니다.
> Update 윤우식 profile

- README.md
- db.yml
* 블로그 주소 정정
* RSS 추가
* 페이스북 삭제 (더이상 페이스북을 하지 않음)
> 블로그 주소 정정 및 RSS 추가

- README.md
- db.yml
> Update 신은광 profile

- db.yml
> 블로그 db.yml 추가 (kbs4674 / 김철민)

- db.yml
> 강교일 블로그 추가

- db.yml
> '최준우' 블로그 추가요청 드립니다.

- README.md
- db.yml
> 박재영 추가요청드립니다.

- README.md
- db.yml
안녕하세요? 어썸데브블로그 잘 사용하고있습니다.
블로그 추가 요청 드립니다.
다른 PR들을 보고 README.md와 db.yml에 내용을 추가하였습니다.
감사합니다.
> 허재영 블로그 추가

- README.md
- db.yml
안녕하세요 
다른분들 수정하신 양식 보고 제 블로그도 추가했습니다.
https://10yearscoder.tistory.com/
감사합니다.
> 10년코더 블로그 추가

- README.md
- db.yml
블로그 주소가 변경되었습니다. 새로운 블로그를 하나 더 추가하였습니다.
> 블로그 주소 변경 및 1개 추가

- domestic_team.md
후이서울(Huiseoul) 기술블로그 추가 요청합니다.
> 후이서울 기술블로그 추가

- README.md
- db.yml
블로그 주소가 변경되어 db 변경 및 readme 추가했습니다. 감사합니다
> 김원호 블로그 주소 변경 및 테이블 추가

- README.md
- db.yml
블로그 주소가 변경되어 db.yml 수정 및 README.md 수정했습니다. 
감사합니다.
> 강준영 블로그 주소 변경 및 테이블 수정

- db.yml
블로그 정보가 너무 오래되어 변경합니다.
페북 URL 및 Twitter 계정 삭제합니다.
> Edit ujuc information.

- README.md
- db.yml
What is this PR ? 🔍
개발자 지찬규 추가를 위한 Pull Request 입니다.
재밌고 유익한 블로그가 많은 레포네요!! 감사합니다! 좋은 내용이 많은 블로그 만들어 볼게요!!
Changes 📝
Added db.yml
Added README.md
> [블로그 추가] 개발자 `지찬규` 추가

- README.md
- db.yml
안녕하세요. 기존 .com 도메인이 만료되어 .dev 도메인으로 변경했습니다. 감사합니다 ^^
> 조은우 블로그 도메인 변경

- README.md
- db.yml
안녕하세요.
손상우 기술 블로그 추가 요청드립니다.^^
감사합니다.
> master/-/손상우 추가

- README.md
- db.yml
안녕하세요.
김상열 개인 블로그 추가 부탁드립니다.
감사합니다.
> 김상열 개인 블로그 추가

- db.yml
> 문동욱 rss 피드, github, linkedin 데이터 추가

- db.yml
> 김중현 rss 피드 추가

- db.yml
양성민 RSS 추가,
tistory 블로그 삭제(미사용)
> 양성민 RSS 추가, 티스토리 블로그 삭제

- README.md
- db.yml
안녕하세요.
김상연 개인 블로그 추가 부탁드립니다.
감사합니다.
> 김상연 개인 블로그 추가

- README.md
README에 블로그 주소 깃헙 주소로 잘못 지정하여 수정합니다.
> 김상연 블로그 주소 수정

- README.md
안녕하세요. awesome-devblog 좋은 프로젝트를 진행해주셔서 정말 감사합니다. :)
다른 프로젝트의 기반 데이터로 사용해도된다고 하셔서
https://awesome-devblog.netlify.com/를 기반으로 텔레그램봇을 제작하였습니다.
혹시 제가 사용하면안될 데이터를 참조하고 있다면 연락주시면 바로 고치도록하겠습니다.
소개글과 프로젝트를 read.me에 추가하였습니다.
감사합니다.
> Update : Read.me에 TodayDevblog_bot 소개글과 프로젝트 추가

- db.yml
> 최준영 블로그 추가

- db.yml
> 최지민 블로그 추가

- db.yml
> 블로그 추가 : 남윤지 블로그 추가

- db.yml
> 유형준 개인 블로그 추가

- db.yml
> 박준우 블로그 추가입니다!

- db.yml
> 이동원 블로그 추가

- db.yml
>  유보미 블로그 추가

- db.yml
안녕하세요.
트래픽 유입이 확인되어서 찾아보니 이런 멋진 곳이 있었네요!
다름이 아니라 수집된 정보 중에서 수정하고 싶은 부분이 있는데요.
관련하여 이 이슈를 생성하고 Pull Request로 수정 요청드립니다.
한가지 더, https://awesome-devblog.netlify.com/domestic 에서
제 실명(김태완)으로 국내 피드를 검색해보았는데요.
링크는 정상 동작하나, 모든 게시글이 동명이인의 이미지로 표기되는 것 같습니다.
감사합니다 :D
> [#209] 정보 수정 요청드립니다 :D

- db.yml
> 지소라 블로그 추가

- db.yml
> 윤경태 블로그 추가

- db.yml
> 염광호 블로그 추가

- db.yml
> 박준우 블로그 주소 수정

- db.yml
> 정해균 블로그 추가

- db.yml
> 김재혁 블로그 추가

- db.yml
안녕하세요! 
개인블로그 추가 PR 드림니다.
감사합니다.
> 한철희 블로그 추가

- db.yml
안녕하세요, 블로그 추가 요청 드립니다!
유용한 서비스를 만들어주셔서 감사합니다🙇‍♂️
> 유정혁 블로그 추가

- db.yml
> 유정혁 블로그 RSS 경로 추가

- domestic_team.md
안녕하세요 44bits.io를 추가하고 싶어서 PR을 보냅니다.
> 44bits.io를 추가하고 싶습니다

- db.yml
- 깃헙 계정 url을 제외한 모든 링크가 깨지거나 비활성화 상태인 사용자를 삭제했습니다.
> Remove broken link

- db.yml
안녕하세요.
오입력된 값이 있어, 업데이트 수정하였습니다. 죄송합니다.
감사합니다 : )
> 이찬구 정보 업데이트

- Korea-Dev-RSS_temp.opml
데브원영 유튜브 채널에서 개발관련 이야기를 공유하고 있습니다.
상기 채널에 대한 rss를 추가하여 PR드립니다. 검토부탁드립니다.
> 데브원영 유튜브 채널 추가

- db.yml
https://github.com/sarojaba/awesome-devblog/pull/238 에서 opml파일이 더이상 관리되지 않음을 확인하였습니다.
이에 따라 db.yml을 업데이트하여 pr드립니다.
> 데브원영 유튜브채널 추가

- db_community.yml
> 커뮤니티 DB에 테크니들 추가

- README.md
> 깨진 링크 수정 (개발블로그 알림서비스 TodayDevblog_bot 개발기)

- db.yml
> 김정헌 rss url 변경

- db.yml
네이버 → 티스토리 으로 블로그를 옮기게 되었습니다 :)
> 김철민 블로그 주소 및 rss 수정

- db.yml
기존 Medium 블로그를 Github Pages로 전환하게 되어 Pull Request 드립니다.
> 이용환 블로그 URL 변경

- db.yml
안녕하세요. 블로그 추가 PR 드립니다.
좋은 서비스 제공해주셔서 감사합니다 :)
> 이현규 블로그 추가

- db.yml
이수진 (lsjsj92.tistory.com) 페이스북 정보 업데이트입니다.
> update soojin facebook

- db.yml
> 윤서현 rss 추가

- db.yml
> remove andrew blog

- db.yml
블로그 추가 PR 요청드립니다.
좋은 서비스 감사합니다! 😊
> 김지훈 블로그 추가

- db.yml
항상 열심히 공부하는 회사 동료 이지민님을 추천 합니다.
감사합니다. ^^
> 이지민 개발자 추가

- db.yml
> 정민정 개발블로그 추가

- db.yml
> 임창현 블로그 추가

- domestic_team.md
[렌딧 기술블로그](https://lenditkr.github.io/) 추가를 요청드립니다!
> 렌딧 기술 블로그 추가

- db.yml
안녕하세요! 블로그 PR드립니다! 개발 열심히 하겠습니다! 감사합니다!
> 블로그 PR 드립니다!

- db.yml
> Add KimReady

- db.yml
> update kimsangyeon blog url

- domestic_team.md
> 팀 기술 블로그 추가를 요청드려요 ☺️

- db.yml
> 양상현 블로그 이전

- db.yml
> 이창섭 추가입니다.

- db.yml
> 이청규 rss 값 변경

- db.yml
> add geon lee info

- domestic_team.md
> NHN(TOAST meetup) 추가

- db.yml
안녕하세요 블로그 이전으로 인한 정보 업데이트 PR입니다.
> 이현규 블로그 이전

- db.yml
> 김준영 rss와 blog 주소 수정

- db.yml
안녕하세요.  
초보 개발자 윤여선입니다.  
Toy-Story 사이드 프로젝트 발표 때 개발자님을 인상깊게 보고 늦게나마 제 블로그 추가 요청 드립니다. :) 
현재 블로그에는 많은 글은 없지만 앞으로 공부한 것 많이 기록해보려고 합니다.
감사합니다 :)
> '윤여선' 블로그 추가

- db.yml
Hi, Thank you for your feed service.
Please add my blog to your feed list.
> Add Choi Soo Hyung(aka wholeman) blog

- db_community.yml
안녕하세요?
컬리 기술블로그를 목록에 추가하는 PR 드립니다.
커밋이나 PR에 대한 규칙을 따로 언급한 글을 찾지 못하여 임의로 메세지 작성하였습니다.
리뷰 부탁드립니다.
감사합니다.
> 컬리 기술블로그를 목록에 추가 합니다.

- db.yml
> 박찬희 블로그 변경

- db.yml
> 보스백 블로그 추가 ( 백규철 ) 

- db.yml
안녕하세요. BLEX라는 블로그 서비스를 만들고 있는 배진오입니다.
Awesome Devblog라는 멋진 프로젝트에 RSS를 올릴 수 있도록 추가하고 보니 영광스럽게도 Awesome Devblog에 링크가 되어있음을 확인했습니다. 어떻게 발견하셨는지 의아함과 신기하단 생각이 많이 들었습니다. 😁
해당 사이트로 등록된 사용자의 RSS를 추가하였고 저도 블로그를 이곳으로 이전하여 블로그 주소를 변경하였습니다. 멋진 서비스 만들어 주셔서 진심으로 감사합니다!
> Added RSS to BLEX

- db.yml
> 이청규 blog, rss 변경

- db.yml
> popl awesome-devblog에 추가

- db.yml
제 블로그 링크를 추가 하였습니다.
확인해보시고 반영 부탁드립니다.
> 신규 개인 블로그 추가(김민석)

- db.yml
제 개인 블로그 추가했습니다.
Merge 부탁드립니다 :)
> 개인 블로그 추가(이현진)

- db.yml
제 개인 블로그 추가했습니다.
netlify.app으로 통일 했습니다
> 정준영 블로그 추가

- db.yml
안녕하세요.
제 개인 블로그 추가하였습니다!
감사합니다:)
> 박장원 개인 블로그 추가

- db.yml
개인 블로그를 추가하려고 보니 이미 되어 있더군요! 
슬라이드쉐어는 더 이상 관리하지 않아서 제거했고, 다른 정보들을 추가했습니다.
> 구영민 데이터베이스 수정

- db_useful_links.yml
Hello, I added extendsclass.com (I am the founder), which provides tools for developers.
> Added an online toolbox for developers

- db.yml
블로그에 domain을 넣어서 기존 DB에 있는 URL 대신 새로운 URL로 업데이트 하였습니다. 
감사합니다. 🙇
> MODIFY: 임창현 데이터베이스 수정

- db.yml
> 조수환 블로그 추가

- db_community.yml
Hello,
I looked at the community blog list and removed items that I couldn't access properly.
If it's against the policy, you can close the PR.
Thank you.
---
Added additional blog links from Skelter Labs. I'd appreciate it if you could review it.
> Remove unreachable blog&rss community links

- db.yml
Change blog and github url
블로그 개편으로 url이 변경되어 직접 변경신청합니다~!
> 한지승 url 변경

- db.yml
- db_community.yml
안녕하세요!
크몽 기술블로그 플랫폼을 변경하여 블로그 주소 변경과, 개인 블로그 추가하는 PR 드립니다.
감사합니다.
> 크몽 기술 블로그 이전 및 개인 블로그 추가

- db.yml
블로그 이전으로 url이 변경되어 변경 요청 드립니다.
> 이현규 블로그 URL 수정

- db.yml
> 정수범 블로그 추가 

- db.yml
블로그 변경이 있어 다시 풀리퀘 보내드립니다. 감사합니다.
> [UPDATE] edit 최승호 blog

- db.yml
이름 순 정렬로 수정 후 다시 부탁드립니다, 번거롭게 해드려 죄송합니다.
> 허전진 블로그 추가 부탁드립니다! (수정)

- db.yml
> 새로운 blog 등록 - 김정준

- db.yml
> update introduce saseungmin

- db.yml
추가내용
- blog
- rss
- github
- description
> 블로그 추가 요청(이경언)

- db.yml
안녕하세요 신입 백엔드 개발자 김민정입니다.
추가 부탁드립니다.
> 김민정 블로그 추가

- db.yml
운영하고 있는 유튜브 링크와 인스타그램 링크를 추가했습니다 🤩
> 노우현 링크 추가 및 description 수정

- db.yml
> MODIFY: 서브 도메인 변경으로 rss변경

- db.yml
> Wonjong Oh 정보 추가

- db.yml
> Add new blog owned by Jeonghyeon Park

- db.yml
> 블로그 추가(Dennis 김동석)

- db.yml
> 개발자 차성원 추가

- db.yml
안녕하세요. 번거롭게 하여 죄송합니다.
Blog rss 추가하여 PR 다시 보냅니다. Merge 부탁드립니다.
감사합니다.
> 강지회 blog rss 추가

- db.yml
> docs: 김동영 추가

- db.yml
> Update : 블로그 추가

- db.yml
안녕하세요! 이전에 사용한 블로그 링크가 적혀있어 현재 사용중인 블로그 링크로 수정했습니다.
또한 추가 정보들을 등록했습니다.
> 박성우 링크 수정/추가

- db_community.yml
코드스테이츠 정보가 예전 것이어서 업데이트 요청합니다.
> 코드스테이츠 정보 업데이트

- db.yml
블로그 추가 요청드립니다. 좋은 서비스 만들어주셔서 감사합니다! :D
> 신서현 블로그 추가 요청

- db.yml
Github 주소와 블로그의 URL 주소가 변경되어 업데이트합니다.
감사합니다.
> 모영진 블로그/github 업데이트

- db.yml
김기완 blog/rss/github//linkedin추가
> 김기완 blog/rss/github//linkedin추가

- db.yml
> add yeojihoon

- db.yml
안녕하세요!
블로그 추가 요청드립니다 👍
감사합니다 :)
> 장지훈 블로그 추가

- db.yml
> add https://devlog.juntae.kim into db.yml

- db.yml
> Update 김정준's rss

- db.yml
> Update 양욱진's blog

- db.yml
> 김재영 추가 요청합니다.

- db.yml
> 최재원 블로그 추가

- db.yml
Hello,
I've corrected the typo in the entry that exists in db.yml.
I would appreciate it if you approve it after review.
Best regards,
luiseok
> [chore] fix some typos on db.yml

- db.yml
> 정재남 rss 추가 요청드립니다.

- db.yml
> Update 장동민's blog

- db.yml
> feat: 김태정 정보 추가

- db.yml
> feat : 김도하 정보 추가

- db.yml
indent 처리가 잘못되었습니다. (그래서 메일링 서비스도 장애(?) 가 났네요 ㅎㅎ..
> yml 문법 오류 수정

- db.yml
> 최지헌 블로그 정보 수정

- db.yml
안녕하세요, 현재 11번가에서 재직중인 조성빈이라고 합니다.
요즘 열심히 블로그를 쓰고 있어서, 홍보차 PR 넣게 되었습니다. 감사합니다.
> Add kadensungbincho

- db.yml
블로그 정보 추가 요청합니다.
가나다 순으로 정렬하였습니다;;
> feat : 박용훈 정보 추가

- db.yml
> jintaelee added

- db.yml
> add jaeseokim

- db.yml
안녕하세요 😄 
블로그 추가 부탁 드립니다 감사합니다 🙇
> add profilie:TaeHyoungKwon

- db.yml
> 오원종 정보 업데이트 (rss 추가)

- db.yml
> refactor: 김태정 블로그 정보 수정

- db.yml
> 블로그 추가합니다.

- db.yml
> 개인 블로그 추가합니다

- db.yml
> rlawnsxo131 rss 주소 변경

- db.yml
> 홍지훈 블로그 추가

- db.yml
> 2021-04-04 Junhyunny's devlog blog add

- db.yml
불필요한 블로그를 제거했습니다.
해당 이슈는 지난주 Discussions에서 논의 했습니다.
> 불필요한 블로그 제거

- db.yml
> 김성호 블로그 주소 변경

- db_community.yml
안녕하세요
큐브리드 기술 블로그 추가 PR 드립니다.
감사합니다.
> 큐브리드 기술 블로그 추가

- db_community.yml
한국 그린데이터
- blog
- rss
- linkedin
> 한국그린데이터 추가

- db_opensource.yml
안녕하세요,
CUBRID 오픈소스 추가 요청드립니다.
감사합니다.
> 큐브리드 오픈소스 추가

- db.yml
> RxSwift 공부한것 정리

- db.yml
> Update db.yml 

- db.yml
> FEAT: 이동욱 블로그 추가

- db.yml
> 최진우 블로그 추가

- db_overseas.yml
- overseas.md
소스 코드 자동 리뷰 솔루션을 개발하고 있는 해외 기업인 `Siderlabs`의 블로그 추가하였습니다.
> Siderlabs 블로그 추가

- db.yml
개인 블로그를 시작하여 새로운 user 추가 요청 pr 드립니다.
> 새로운 user 추가 요청

- db.yml
> 김주엽 블로그 수정

- db.yml
> 오재욱 블로그 추가

- db_community.yml
도모버스 팀블로그를 추가했습니다.
* Medium Blog
* RSS
> 도모버스 팀블로그 추가

- db.yml
> 이주현 블로그 추가

- db.yml
> 정승현 기술 블로그 추가 

- db.yml
> 이충현 블로그 추가

- db.yml
> 정필규 블로그 추가

- db.yml
- 서경석 개인 블로그 추가
- db.yml 코드에 뒷공백 일부 수정(사실 개발환경에 lint걸려있어서;;;)
- rss을 atom.xml로 수정했는데 feed.xml(rss2.0)도 같이 되긴 하는데 일단 atom.xml로 db.yml에는 넣어두었습니다.
> 서경석 블로그 추가

- db.yml
> 정유택 블로그 주소 수정

- db.yml
> 손수민 블로그 추가

- db_community.yml
DEVOCEAN(데보션) 커뮤니티 단체 블로그 추가 요청 드립니다. ^^
> DEVOCEAN(데보션) 커뮤니티 단체 블로그 추가

- db.yml
> kim-beak blog add

- db.yml
블로그를 이전하게 되어 업데이트 합니다.
항상 감사드립니다.
> 조동현 블로그 수정

- db.yml
우선 좋은 서비스 운영해주셔서 정말 감사합니다!😊
구독해서 매번 보다가 제 블로그 추가해봅니다!
궁금한 점이 있는데 동명이인이 있어서 그런데 혹시 문제가 없을까요?
> 박소현 블로그 추가

- db.yml
> 이현우 블로그 추가

- db.yml
https://github.com/sarojaba/awesome-devblog/issues/551 확인 부탁드립니다.
> feat: [#551] 김이안(구 김찬미) 정보변경

- db.yml
> 한구영 블로그 추가

- db.yml
> 김종혁 블로그 추가

- db.yml
> add:onedayz blog info

- db.yml
> 홍준혁 블로그 추가

- db.yml
> db.yml에 블로그 추가

- db.yml
제 이름은 이미 추가되어있는데, 거기에 description과 tistory를 추가했습니다!
> 정현수 description, tistory 추가

- db.yml
> 김석현 블로그 추가

- db.yml
안녕하세요. 
블로그 rss 주소가 수정 되어서 pr 요청드립니다.
> 박승현 rss 주소 수정

- db.yml
등록방법 읽고 다시 작성해서 보냅니다ㅠ
김종현 blog 추가 부탁드립니다
> 김종현 blog  추가

- db.yml
링크는 모두 검수 했으며 형식 등 수정되어야 하는 부분이 있으면 코멘트 부탁드립니다 !
> 데이터 등록 요청드립니다 !

- .github/FUNDING.yml
- db.yml
안녕하세요 백엔드 개발자로 일하고 있는 박정우 입니다.
잘부탁드립니다~
> 안녕하세요 ~ 잘부탁드립니다 !🙌

- db.yml
블로그 티스토리 이전으로 인한 링크 수정 및 RSS 링크를 추가 하였습니다.
> 정승현 블로그 수정

- db.yml
> 김정식 블로그 추가

- db.yml
추가 부탁드립니다! 좋은 서비스 운영해 주셔서 감사합니다!
> deleve devblog 추가

- db.yml
> newdeal 블로그 추가

- db.yml
예전부터 구경하고 있었는데,
오늘에서야 블로그 등록하는 법을 알게 되어서 신청합니다!
잘부탁드립니다!
> 김동효 블로그 추가

- db.yml
안녕하세요! 항상 노고에 감사드립니다.
저 이수진(lsjsj92) 계정의 linkedin url이 잘못 되어 있어서 이를 수정하였습니다!
PR 받아주시면 감사하겠습니다.
> modify lsjsj92(leesoojin) linkedin url

- db.yml
서비스 잘 쓰고있다가 블로그 작성을 시작해서 추가 요청 드립니다.
> 블로그 추가 요청드립니다.

- db.yml
> 권혁우 블로그 추가 요청

- db.yml
> 윤석진 블로그 추가

- db.yml
> 등록하고 싶습니다 ㅎ

- db.yml
안녕하세요.
이재준 입니다.
개인적으로 정리중인 블로그 추가 요청드립니다.
- 이재준 블로그 등록 요청
- 주소: https://jx2lee.github.io/
> 이재준 블로그 추가

- db.yml
> add moonsiri

- db.yml
> 최수혁 블로그 추가

- db.yml
> 최병현 블로그 추가

- db_community.yml
안녕하세요.
테이블링 기술블로그 추가 요청합니다.
감사합니다.
> 테이블링 기술블로그 추가

- db.yml
안녕하세요.
|@donghl-dev 블로그 주소 추가 요청드립니다.
미리 감사드립니다.
> 안녕하세요. 블로그 주소 추가 요청드립니다.

- db.yml
안녕하세요, 김이안입니다.
혼자 보기 아까운 블로그가 있어서 추가했습니다.
더불어, 제 정보도 업데이트하여 PR 요청합니다.
확인 부탁드립니다.
> 엄승하 님 추가 외 수정사항 반영 요청

- db.yml
> add: 김정환 블로그 추가

- db.yml
> 박태진 rss 주소 변경

- db.yml
> 삭제요청 부탁드립니다.

- db.yml
> 김성중 블로그 추가

- db.yml
안녕하세요!
FE 개발 하고 있는 위정훈입니다
블로그 추가 요청 드립니다
> 위정훈 블로그 추가 요청

- db.yml
> 박동현 블로그 추가

- db.yml
> 이재두 블로그 추가

- db.yml
> Devlee247 블로그 추가

- db.yml
> 안희찬 프로필 추가

- db.yml
> 신원준 블로그 추가

- db.yml
안녕하세요, 블로그 주소를 변경해서 PR 드립니다.
이렇게 PR 날리는게 맞나요?
> 유형곤 블로그 변경

- db.yml
> 강경석 블로그 추가

- db_community.yml
안녕하세요, 저는 채널코퍼레이션의 백엔드 엔지니어 정연길입니다,
채널 코퍼레이션 rss 링크 추가 PR 요청 드립니다, 감사합니다 :)
> 채널코퍼레이션 블로그 rss 추가

- db.yml
> bmh8993 블로그 추가

- db_community.yml
> Trenbe 기술블로그 추가

- db.yml
> 신원준 블로그 변경

- db.yml
> 이상원 github 주소 업데이트

- db.yml
> 박찬영 기술 블로그 추가

- db.yml
권시연 개인 블로그 추가 요청 드립니다!
(+)
다른 분거 건드리면 안될 것 같아서 냅뒀는데 한재엽님 facebook 주소가 두번 들어가서 에러가 뜨네요!
> 개인 블로그 추가 요청

- db.yml
> Add shirohoo blog

- db.yml
> Add Frankle blog

- db.yml
> 김창회 기술 블로그 추가

- db.yml
예전에 작성해둔 인적사항에 블로그 및 rss.xml 추가하였습니다. 수정 반영 부탁드립니다.
> 한종우 개인 기술블로그 추가

- db.yml
> 유재상 기술 블로그 추가

- db_community.yml
안녕하세요. AB180 정주홍입니다.
저희 기술 블로그 추가 요청 드립니다.
> AB180 기술 블로그 추가

- db.yml
> add junghyunlyoo

- db.yml
> 박경선 기술 블로그 수정

- db.yml
#659 db.yml 리스트 형식 오류
해당 이슈 수정입니다.
> 개인 블로그 리스트 형식에 맞게 수정

- db.yml
> 김진주 블로그 추가

- db.yml
링크드인과 페이스북 링크 수정하였습니다. 반영 부탁드립니다.
> 반정훈 기술 블로그 소셜 링크 수정

- db.yml
- 기존 atom.xml 형태에서 rss.xml형태로 수정
- 불필요 공백제거
> 서경석 블로그 rss 링크 수정

- db.yml
블로그를 추가하고 싶습니다.! 머지해주시면 감사하겠습니다.
> 김민재 블로그 추가

- db.yml
> 윤태희 블로그 추가

- db.yml
인적사항에 트위터 링크 추가하였습니다. 반영 부탁드립니다.
> 한종우 소셜 링크 추가

- db.yml
> [신규 블로그 추가] www.sueaty.com 추가

- db_community.yml
> 딜리셔스 기술블로그 추가

- db.yml
> [블로그 주소 수정] 조수정 블로그 링크 수정

- db.yml
add techblog twjh_awesomedevblog
branch: twjh_awesomedevblog
> add techblog twjh_awesomedevblog

- db_community.yml
- 카카오페이의 blog, linkedin을 추가합니다.
- rss 등 추가정보는 추후 업뎃하겠습니다.
> docs: 카카오페이 추가

- db.yml
> Add joonas

- db_community.yml
안녕하세요~ 딜리셔스 기술블로그 rss 추가요청드립니다!
> 딜리셔스 rss 추가

- db.yml
개인 기술 블로그 주소 추가하고자 합니다.
가이드에 따라 **실명** 및 **RSS** 내역 반영하였습니다.
> 박재규 블로그 추가

- db.yml
티스토리 백엔드 블로그
https://thalals.tistory.com/
> 박형민 블로그 추가 부탁드리겠습니다~

- db_community.yml
- STCLab tech blog
- 에스티씨랩 기술 블로그
추가 부탁드립니다. 서비스 감사합니다.
> add STCLab tech blog

- db.yml
오명균 블로그 추가 부탁드립니다! 감사합니다 : )      (Notion + oopy 연동으로 만든 블로그라 글을 가져올 수 있을지 모르겠네요..!)
> db.yml에 블로그 주소 추가

- db.yml
> change blog address - 이성일

- db.yml
손영인 블로그 추가 부탁드립니다~
auto formatting 때문에 공백 수정이 되어버렸는데 고쳐야하면 말씀해주세요!!ㅠ
> 손영인 블로그 추가

- db_community.yml
카카오스타일 기술 블로그 관련 항목을 수정했습니다.
- 타이틀, 링크 수정 및 추가
- RSS 추가
> fix: 카카오스타일 항목 수정

- db.yml
> add: rss 주소 변경되었습니다.

- db.yml
root-devvoo(정우철) 블로그 추가 부탁드립니다. :)
pull request 한번 생성했다가 수정 할 부분 발견해서 수정 후 다시 올립니다.
번거롭게 해드려서 죄송합니다 ! 🙏
> root-devvoo(정우철) 블로그 추가

- db.yml
> 김경철 블로그 추가

- db.yml
> 강석재 블로그 추가

- db.yml
블로그 추가 요청드립니다! 개인적으로 공부한 내용을 기록하는 곳입니다!
> 블로그 업데이트 요청

- db.yml
안녕하세요.
박지성이라고 합니다.
읽기만 했는데 저도 글을 쓰고 저의 생각을 공유하고 싶어서 시작했습니다.
아직 글은 많이 없지만 열심히 해보려합니다.
감사합니다.
> 박지성 블로그 추가

- db.yml
기존 기술 블로그 주소에서 다른 기술 블로그 주소로 변경 요청 드립니다.
> 정승현 기술 블로그 주소 변경

- db.yml
> 이재영 블로그 변경

- db_community.yml
> 카카오페이 rss 추가

- db.yml
> 이준석 블로그 추가

- db.yml
> 정현수 블로그, RSS 업데이트

- db.yml
안녕하세요. 안동원입니다.
매일 아침마다 공유되는 글을 보면서 많이 배우고 있는데, 
제가 작업한 내용도 공유되면 일부 분들에게 도움이 될 수 있겠다 싶어 추가 요청드립니다.
감사합니다.
> 안동원 블로그 추가

- db.yml
안녕하세요!
이번에 github user name 을 변경하고, 이것에 맞춰서 블로그 이전을 해서 주소변경 요청드립니다!
감사합니다.
> 박정욱 블로그 업데이트

- db.yml
> 김종진 블로그 추가

- db_community.yml
안녕하세요.
차라투 기술블로그 추가하였습니다. 🙇
감사합니다.
> 차라투 기술블로그 추가

- db.yml
> 노서현 블로그 추가

- db.yml
> 김가은 블로그 주소 수정

- db.yml
블로그 url이 도메인으로 변경하게 되어서 수정 요청드립니다!
> 김동효 블로그 수정

- db.yml
제 lint가 적용되어서 취소하고 다시 블로그 신청합니다!
> 고범수 블로그 추가

- db.yml
> 송도윤 블로그 추가

- db.yml
> 황세영 추가 부탁드립니다!

- db.yml
> 정건영 추가 부탁드립니다

- db.yml
[정규호 블로그](https://katfun.tistory.com/) 추가 pr입니다.
> 정규호 블로그 추가

- db.yml
최영주 블로그 추가 부탁드립니다!
개인 개발 또는 공부가 위주이며, Android를 기반으로 Flutter을 사용 중입니다!
> 최영주 블로그 추가

- db.yml
정현우 블로그 추가 요청드립니다.
양질의 콘텐츠 매일 잘 읽고 있습니다, 감사합니다 👍👍
> 정현우 블로그 추가

- db.yml
Hohyeon Moon 블로그 외의 주소 제거 부탁드립니다!
> Hohyeon Moon 블로그 외의 주소 제거

- db.yml
> 블로그 등록 요청드립니다.

- db.yml
김종엽 블로그 추가 부탁드립니다.
블로그 주소는 https://jykim74.tistory.com 입니다.
> jykim74 tistory register

- db.yml
> 김관희 블로그 추가

- db.yml
- 블로그 개편으로 인한 정보 최신화 
- description 변경
-  nickname 추가
> Updated db information related to 정범희

- db.yml
> Jihoon Ahn 블로그 추가

- db.yml
> 유수민 블로그 추가

- db.yml
> 한진탁 블로그 추가

- db.yml
devage.tistory.com -> devage.info 변경에 의한 업데이트
> 박일균 블로그 수정

- db.yml
황선태 블로그 추가 부탁드립니다!
프론트엔드 분야의 다양한 글을 올릴 예정입니다. 갑사합니다 :)
> 황선태 블로그 추가

- db.yml
도메인 업데이트
besfir.github.io => besfir.xyz
> 도메인 주소 업데이트로 인해, 수정 요청드립니다.

- db.yml
> 박경준 Blog URL수정

- db.yml
정우철: Linkedin 링크 수정으로 인한 풀 리퀘스트 요청드립니다.
> 정우철_Linkedin 링크 수정

- db.yml
Reverts awesome-devblog/awesome-devblog#773
> Revert "정윤재 블로그 추가"

- db.yml
블로그를 추가하고 싶습니다 :)
머지해주시면 감사하겠습니다.
> 조예지 블로그 추가

- db.yml
> 변지혜 블로그 추가

- db.yml
> 김혜빈 개인블로그 업데이트 했습니다!

- db_community.yml
QuotaLab 기술 블로그가 추가되어 PR 올립니다.
좋은 커뮤니티를 운영해주셔서 감사합니다!
> QuotaLab 기술 블로그 추가

- db.yml
> 채정아 블로그 추가

- db.yml
> 이현우 블로그 및 개인 정보 수정

- db.yml
> Modified rss url

- db.yml
[정규호 블로그](https://kchung1995.github.io) 변경 pr입니다.
tistory -> github으로 플랫폼 변경
> update: 정규호 블로그 주소 변경

- db.yml
- db_community.yml
[blog.hodory.dev](https://blog.hodory.dev/) RSS 주소 변경됨
[blog.jaemyeong.com](https://blog.jaemyeong.com/) rss 주소 변경됨
[mkseo.pe.kr](https://mkseo.pe.kr/) blog2, rss2 항목 접속 불가로 삭제
[abeldaos.tistory.com](https://abeldaos.tistory.com/) 티스토리 삭제된 블로그
[aidanbae.github.io](https://aidanbae.github.io/) delete blog 커밋으로 레포지토리 비움
[pabii.co.kr](http://pabii.co.kr/) 다른 도메인으로 리다이렉션되므로 제거
[cjaewon.com](https://c.cjaewon.com/) 깃허브 페이지 404
[iamseapy.com](https://iamseapy.com/) {"message:":"Hello World"}
[coding8282.tistory.com](https://coding8282.tistory.com/) 삭제된 티스토리 블로그
[dev-daddy.tistory.com](https://dev-daddy.tistory.com/) 삭제된 티스토리 블로그
[jx2lee.github.io](https://jx2lee.github.io/) 깃허브 페이지 404
[knphouse.tistory.com](https://knphouse.tistory.com/) 삭제된 티스토리 블로그 …
> 접속 불가능한 블로그 제거 및 일부 블로그 RSS 변경 2

- db.yml
> add, db.yml: jak010 blog append

- db.yml
안녕하세요.
블로그 정보 추가 요청드립니다.
항상 잘 구독하고있습니다.
감사합니다.
> add: 이동근 추가

- db.yml
rss feed 경로 수정 반영 부탁 드립니다 _ _)
> 최성기 : 블로그 rss 링크 변경사항 업데이트

- db.yml
> 구성우 블로그 추가

- db.yml
> 오형근 블로그 추가

- README.md
> 형제자매 프로젝트 링크 수정

- db.yml
> 연서은 블로그 주소 변경

- db.yml
개발 외적인 내용들을 올리려 계획중이어서, 서비스 취지에 맞지 않아 삭제를 요청합니다.
> 블로그 정보 제거

- db.yml
오타 수정
backjoon -> baekjoon
codeforce -> codeforces
desciprion -> description
desciption -> description
descriptoin -> description
youtbue -> youtube
> typo 오타 수정

- db_community.yml
PR 754 에 대한 fix
[#754](https://github.com/awesome-devblog/awesome-devblog/pull/754)
> fix PR 754

- db.yml
안녕하세요 😀
블로그 추가 요청 드립니다. 감사합니다.
> 윤종원 개발 블로그 추가

- db_community.yml
안녕하세요~ 지마켓 기술블로그 정보를 추가합니다.
감사합니다.
> G마켓 기술블로그 추가

- db.yml
> 김보경 블로그 등록 요청

- db.yml
> 손영신 블로그 추가

- db.yml
> 박시형 블로그 추가

- db.yml
김현지 블로그 추가하였습니다!
확인 부탁드리겠습니다🤓!
> Docs: add blog address to db.yml

- db.yml
> 이창훈 블로그 추가

- db.yml
> 황진성 블로그 추가

- db.yml
> 구영표 블로그 추가

- db.yml
blog의 도메인이 변경되어 업데이트 하여 PR 드립니다.
> 이동원 블로그 정보 업데이트

- README.md
```diff
- - [국내 개발 블로그/유튜브 모음](https://kr-open-development.github.io/), [Github](https://github.com/kr-open-development/kr-open-development.github.io)
```
> 형제자매 프로젝트 - 제거된 프로젝트

- db.yml
> 김용건 블로그 추가 요청

- db.yml
> feat: update user db

- db.yml
> 김해준 블로그 추가

- db.yml
> blog, rss가 변경되어 수정 PR 넣습니다!

- db.yml
> 최현정 블로그 추가

- db.yml
박한수 개인 블로그 추가하고 싶습니다!
몇년째 devblog 보며 항상 도움많이 받고 있습니다~ 수고하세요!
> 박한수 블로그(개인) 추가

- db.yml
> 이주함 블로그 수정

- db.yml
> 최우성 블로그 추가

- db.yml
> feat: add profile data to db

- db.yml
> 조현우 블로그 추가

- db.yml
정우철 블로그 수정하였습니다. 확인 후 반영 부탁드립니다.
> 정우철 블로그 수정

- db.yml
안녕하세요 !! 블로그 글들 구독 잘 받고 있습니다 🙇
손현경 블로그 추가 요청드립니다 !
> 손현경 블로그 추가

- db.yml
블로그를 tistory에서 velog로 이전했습니다. 머지 부탁드립니다.
> 박정현 블로그 변경

- db.yml
> 박일균 블로그 삭제

- db.yml
> 송규빈 블로그 추가

- db.yml
블로그 추가 부탁드립니다~! 항상 좋은 글들 공유해주시는 덕분에 많은 공부 되고 있습니다.
> 김현우 블로그 추가

- db.yml
블로그 추가 부탁드립니다~
덕분에 좋은 글들 잘 읽고 있습니다..!
> 김진성 블로그 추가

- db.yml
> 권나영 블로그 추가

- db.yml
> 김예은 블로그 추가

- db.yml
> 박석희 블로그 추가

- db.yml
> 윤석진 블로그 변경

- db.yml
> 김민우 블로그 추가

- db.yml
> db.yml: update 안이수

- db_community.yml
> fix: 인티그레이션 블로그, rss, home 추가

- db.yml
> 박진현 블로그 추가

- db.yml
> 정범희 블로그 수정

- db.yml
> henac 블로그 추가

- db.yml
> chore: 윤우식 정보 업데이트

- db.yml
AI, MLOps 관련 개인 블로그 추가 요청드립니다. 감사합니다!
> 오서영 개인블로그 추가

- db.yml
> 임의상 블로그 추가

- db.yml
안녕하세요. 프론트엔드 개발자 송가영입니다.
블로그 추가 부탁드립니다!
> 송가영 블로그 추가

- db.yml
안녕하세요. 웹 개발자 홍의영 입니다.
블로그 추가 부탁 드립니다 :) 
항상 잘 보고 있습니다. 감사합니다!
> 홍의영 블로그 추가

- db.yml
> 천강민 블로그 추가

- db.yml
안녕하세요.
제 과거 블로그 정보가 적혀있는걸 발견하고 갱신을 위해 PR 요청 드립니다!
> 송경근 블로그 변경

- db.yml
> 이수빈 블로그 추가

- db.yml
> 임주원 블로그 추가

- db.yml
refer #884
강화수: https://hwasurr.io
김덕홍: http://insanehong.kr/
김상연: https://kimsangyeon-github-io.vercel.app/
김종진: https://logonme.net/
김현지: https://www.morolog.dev/
남윤지: https://sehajyang.github.io
모상우: https://brunch.co.kr/@aidenswmo
박지원: https://www.jiwon.me/
배성혁: https://debop.tumblr.com/
Steve Park: https://brunch.co.kr/@stevepark
소용환: https://www.sauru.so/
이동근: https://shylog.com/
이승우: https://blog.2dal.com/
이영찬: https://blog.0chan.dev/
정승현: https://www.roach-dev.com
조준호: http://tmmse.xyz/author/junho/
유재상: https://devlog.jsyoo5b.net/ko/index.xml
김석영: https://tech.zzizily.com/ (cloudflare 로 피드 접근 불가)
> 비활성 블로그 삭제

- db.yml
> add 김태윤 blog

- db.yml
삼성 테크블로그 피드 등록하였습니다. 추가 부탁 드립니다.
> 삼성 테크블로그 피드 추가 요청

- db.yml
> 이상현 블로그 추가

- db.yml
> 김도현 블로그 추가
